version: "3"

volumes:
  postgres-data: {}
  redis-data: {}

services:
  publisher:
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - consumer

  consumer:
    build:
      context: .
    volumes:
      - .:/app
    command: ["python", "consumer.py"]
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
