version: "3"

volumes:
  postgres-data: {}
  redis-data: {}

services:
  processor:
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    entrypoint: /app/entrypoint.sh
    command: ["python", "processor.py"]

  worker:
    build:
      context: .
    volumes:
      - .:/app
    command: ["celery", "-A", "tasks", "worker", "--loglevel=info"]
    depends_on:
      - processor

  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
